### PR TITLE
Typos & french language support

### PR DESCRIPTION
**Pull request by SUBnet192**

### CODE REVIEW

**Comment by PrzemyslawKlys** [comment]
Since you're renaming function please add alias with old name. I know it's wrong, but still we need to at least support old version. I have Supress in PSWriteWord that needs to be Suppress for like 50 commands but I need to add aliases as well.

**Comment by SUBnet192** [comment]
ouch. I would simply implement a required version for dependencies instead of doing that...

**Comment by PrzemyslawKlys** [comment]
I can fix my stuff. But do you know who is using PSWriteWord or ADEssentials or other commands? Looking at PSGallery there are loads of people using it.

**Comment by SUBnet192** [comment]
I understand. For your own dependencies it's fixable. Anyone who updates will get the new corrected names and would have to fix their own scripts for it. I think that's fair. As long as there's a heads-up somewhere in a readme file or something. Your call :) I know I wouldn't, otherwise I'd be dragging these aliases forever.

**Comment by SUBnet192** [comment]
Where do you want me to define these aliases?

**Comment by PrzemyslawKlys** [comment]
As with most of my commands:

```powershell
Function New-HTML {
    [alias('Dashboard')]
    [CmdletBinding()]
    param(
```

It shouldn't be a problem to have aliases like that. It's added once and I'll remove it at some point. You could always update readme as well :)

**Comment by SUBnet192** [comment]
Like this?

Function Get-WinADPrivilegedObjects {
                [alias('Get-WinADPriviligedObjects')]
    [cmdletbinding()]
    param(

**Comment by PrzemyslawKlys** [comment]
Yep ;)

**Pull request merged**
